In [1]:
import numpy as np

In [8]:
# Create an arrasy using numpy
arr = np.array([1,2,34])
print(arr)
print(type(arr))
print(arr.shape)

[ 1  2 34]
<class 'numpy.ndarray'>
(3,)


In [31]:
arr2 = np.array([1,2,3,4])
print(arr2.reshape(2,2))
print(arr2)
print(arr2.shape)

[[1 2]
 [3 4]]
[1 2 3 4]
(4,)


In [39]:
# 2D Array
arr2 = np.array([[1,2], [3,4]])
print(arr2)
print(arr2.shape)

[[1 2]
 [3 4]]
(2, 2)


In [41]:
np.arange(0, 10, 2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [42]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [45]:
## Identity Array 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
# Attribute of numpy

arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr) 
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size (Number of elements): ", arr.size)
print("Datatype: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (Number of elements):  6
Datatype:  int32
Item size (in bytes):  4


In [54]:
# NumPy Vectorize Operation 

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10, 20, 30, 40, 50])

### Element wise addition 
print("Addition: ", arr1 + arr2)

### element wise subtracion
print("Subtraction", arr1 - arr2)

## Element wise multiplication
print("Multiplication: ", arr1 * arr2)

### Element wise Division
print("Division: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Subtraction [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [57]:
## Universal Function
arr = np.array([2,3,4,5,6])

## Square root 
print(np.sqrt(arr))

## Exponential 
print(np.exp(arr))

## Sine 
print(np.sin(arr))

## natural log 
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [61]:
# Array Slicing and Indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
print(arr[0][0])
print(arr[0:2, 2:])

1
[[3 4]
 [7 8]]


In [68]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [71]:
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [73]:
## Modify array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [74]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [78]:
## Statistical concept-- Normalization
## to have a mean of 0 and standard deviation
data = np.array([1,2,3,4,5])

# Clculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
print("Mean: ", mean)
print("Standard deviation: ", std_dev)

# Normilization the data 
normalized_data = (data - mean) / std_dev
print("Normalized data: ", normalized_data)



Mean:  3.0
Standard deviation:  1.4142135623730951
Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [86]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Variance
mean = np.mean(data)
print("Mean: ", mean)

# Median
median = np.median(data)
print("Median: ", median)

# Standard deviation
std_dev = np.std(data) 
print("Standard devision: ", std_dev)

# Variance
variance = np.var(data)
print("Variance: ", variance)

Mean:  5.5
Median:  5.5
Standard devision:  2.8722813232690143
Variance:  8.25


In [98]:
# Logical Operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data[data > 5])
print(data[(data>=5) & (data<=8)])

[ 6  7  8  9 10]
[5 6 7 8]
